<a href="https://colab.research.google.com/github/yohan2001colombo/pyTorch/blob/main/pytorch_practise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Data Manipulation

In [1]:
import torch

In [2]:
x = torch.arange(12,dtype=torch.float32)
x # vector

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [3]:
x.numel()

12

In [5]:
x.shape

torch.Size([12])

In [11]:
X = x.reshape(3,4) # matrix
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [9]:
torch.randn(3,4)

tensor([[-0.4868,  0.6471, -0.1786, -3.0170],
        [-0.6545, -0.2526, -1.5603,  0.6167],
        [ 0.7796,  1.9662,  0.7697, -0.4943]])

### Indexing and Slicing

In [12]:
X[-1] , X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [13]:
X[1,2]

tensor(6.)

In [14]:
torch.exp(x)

tensor([1.0000e+00, 2.7183e+00, 7.3891e+00, 2.0086e+01, 5.4598e+01, 1.4841e+02,
        4.0343e+02, 1.0966e+03, 2.9810e+03, 8.1031e+03, 2.2026e+04, 5.9874e+04])

In [15]:
X.shape

torch.Size([3, 4])

In [16]:
x1 = torch.tensor([1,0,2,4,8])
x1+x1

tensor([ 2,  0,  4,  8, 16])

In [36]:
y = torch.tensor([[1,2,3],[4,5,5]])
y.shape
x3 = torch.tensor([4,5,6])
x3 = x3.reshape((1,3))

torch.cat((y,x3),dim=0)

tensor([[1, 2, 3],
        [4, 5, 5],
        [4, 5, 6]])

In [33]:
x3

tensor([4, 5, 6, 7, 8, 9])

In [37]:
a = torch.arange(3).reshape((3,1))
a

tensor([[0],
        [1],
        [2]])

In [39]:
b = torch.arange(3)
b = b.reshape((3,1))
b

tensor([[0],
        [1],
        [2]])

In [40]:
before = id(y)
before
y = y+y


132309240975184

In [44]:
# to get the item
c = torch.tensor([4])
c.item() # to get one value

4

### Reading the Dataset

In [46]:
import pandas as pd

data = pd.DataFrame({'x1':[1,2,3,4,5,6],'x2':[4,5,6,7,8,9],'y':[7,4,5,3,2,1]})
data.head()

x1  x2  y
0   1   4  7
1   2   5  4
2   3   6  5
3   4   7  3
4   5   8  2

In [50]:
target = data.iloc[:,2]
inputs = data.iloc[:,0:2]

In [54]:
# Conversion to the Tensor Format
X = torch.tensor(inputs.to_numpy(dtype=int))
y = torch.tensor(target.to_numpy(dtype=int))

X,y

(tensor([[1, 4],
         [2, 5],
         [3, 6],
         [4, 7],
         [5, 8],
         [6, 9]]),
 tensor([7, 4, 5, 3, 2, 1]))

In [55]:
# Vectors
x = torch.arange(4)
y = torch.tensor([1,2,3,4])
x,y

(tensor([0, 1, 2, 3]), tensor([1, 2, 3, 4]))

In [57]:
x[0]

tensor(0)

In [58]:
X = x.reshape(2,2) # matrix denoted as capital letters

tensor([[0, 1],
        [2, 3]])

In [59]:
X.T

tensor([[1, 2, 3, 4, 5, 6],
        [4, 5, 6, 7, 8, 9]])

In [ ]:
# Each image arrives as a 3rd order tensor with axes corresponding to the height, width, and channel

In [60]:
torch.arange(24).reshape(2,3,4)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [61]:
X.sum()

tensor(60)

In [62]:
u = torch.tensor([3,-4])
torch.norm(u)

RuntimeError: linalg.vector_norm: Expected a floating point or complex tensor as input. Got Long

### A Simple Function

In [63]:
x = torch.arange(4)

In [64]:
x

tensor([0, 1, 2, 3])

In [1]:
!pip install d2l

In [2]:
from d2l import torch as d2l